Repository HumanCellAtlas/data-store, pull requests merged in 2018-04, with the labels that each got.

#1102 [easy] add gs checkout bucket to environment.prod
  environment.prod
Labels: Q2, production deployment

#1109 fixed logging from lambdas by add logger name 'app'
  dss/logging.py
Labels: in progress

#1112 Add lambda:CreateEventSourceMapping permission
  iam/policy-templates/ci-cd.json
Labels: in progress

#1119 Add more sanity checks to release automation
  scripts/release.sh
Labels: in progress

#1113 Fix: json_generator will not generate numbers that are a multipleOf a…
  dss/util/json_gen/generator.py
  tests/test_jsongenerator.py
Labels: in progress

#1123 [reduce-lambda-usage 2/2] Don't run lambdas unnecessarily.
  dss/stepfunctions/s3copyclient/implementation.py
Labels: in progress

#1074 Reprocess Step Function StartExecution call throttling
  daemons/Makefile
  daemons/build_deploy_config.sh
  daemons/dss-dlq-reaper/.chalice/config.json
  daemons/dss-dlq-reaper/README.md
  daemons/dss-dlq-reaper/app.py
  daemons/dss-dlq-reaper/domovoilib/.keep
  daemons/dss-dlq-reaper/requirements.txt
  daemons/dss-dlq-reaper/vendor.in
  daemons/dss-scalability-test/app.py
  daemons/dss-sfn-launcher/.chalice/config.json
  daemons/dss-sfn-launcher/app.py
  daemons/dss-sfn-launcher/domovoilib/.keep
  daemons/dss-sfn-launcher/requirements.txt
  dss/stepfunctions/__init__.py
  dss/util/aws/__init__.py
  environment
  iam/policy-templates/dss-dlq-reaper-lambda.json
  iam/policy-templates/dss-sfn-launcher-lambda.json
  scripts/deploy_scale_dashboard.py
Labels: Q2, Scale, in progress

#1133 Fix integration test issues related to async SFN invoke semantics
  chalice/build_deploy_config.sh
  daemons/dss-checkout-sfn/app.py
  dss/api/bundles/checkout.py
  iam/policy-templates/dss-lambda.json
  tests/test_visitation.py
Labels: in progress

#1134 Reaper circumvention requires json string.
  dss/stepfunctions/__init__.py
  dss/stepfunctions/visitation/__init__.py
Labels: in progress

#1135 iam policy for cw timer event
  iam/policy-templates/ci-cd.json
Labels: in progress

#1136 [easy] Allow Travis to run tests of reliable notifications (connected to #1100)
  iam/policy-templates/ci-cd.json
Labels: in progress

#1139 checkout bucket in fixture config
  dss/config.py
  tests/test_config.py
Labels: in progress

#1142 Add API Gateway to scale test dashboard
  scripts/deploy_scale_dashboard.py
Labels: in progress

#1143 add symlink vendor.in
  daemons/dss-sfn-launcher/vendor.in
Labels: in progress

#1145 Checkout: make email optional
  daemons/dss-checkout-sfn/app.py
  dss-api.yml
  dss/api/bundles/checkout.py
  tests/test_checkout.py
Labels: checkout, in progress

#1146 Remove checkout fixture bucket requirement
  README.md
  dss/config.py
  environment
  iam/policy-templates/ci-cd.json
  scripts/authorize_aws_deploy.sh
Labels: in progress

#1151 Remove email from the checkout smoketest
  daemons/dss-checkout-sfn/app.py
  tests/test_smoketest.py
Labels: in progress

#1147 [1/2] New PUT /bundle error incorrect_file_bundle_uuid
  dss-api.yml
Labels: in progress

#1159 [2/2] Retry get file blob if not found else raise error (fixes #1115)
  dss/index/bundle.py
Labels: in progress

#1148 [2/2] New PUT /bundle error incorrect_file_bundle_uuid
  dss/api/bundles/__init__.py
  tests/test_bundle.py
Labels: in progress

#1174 [easy] Fix: Visitation instances inadvertently alter the state spec
  dss/stepfunctions/visitation/__init__.py
Labels: in progress

#1127 refactor dss scalability test not to use dss.stepfunctions.generator
  daemons/dss-scalability-test/app.py
Labels: in progress

#1125 nuke dss.stepfunctions.generator
  dss/stepfunctions/generator/__init__.py
  dss/stepfunctions/generator/parser.py
  dss/stepfunctions/generator/types.py
Labels: in progress

#1183 Add an L1 health check endpoint
  chalice/app.py
Labels: in progress

#1185 [Easy] Give travis access to relay secrets
  iam/policy-templates/ci-cd.json
  scripts/authorize_aws_deploy.sh
Labels: in progress

#1182 [3/3] Reliable notifications
  tests/test_smoketest.py
Labels: in progress

#1184 The Big Red Button: Script for an emergency halt of the DSS
  scripts/dss-start-stop--think-before-you-invoke-me.py
Labels: in progress

#1186 Match owner strictly when listing subscriptions
  dss/api/subscriptions.py
Labels: in progress

#1191 cloud-blobstore 2.1.1 for better error messages on BlobNotFoundError
  requirements.txt
  requirements.txt.in
Labels: in progress

#1188 Extend Elasticsearch timeout on Travis from 10s to 30s
  .travis.yml
  dss/index/es/__init__.py
  tests/test_doctests.py
Labels: in progress

#1193 requirements-dev.txt.in should source requirements.txt.in
  requirements-dev.txt.in
Labels: in progress

#1195 Fix cloud-blobstore dep
  requirements-dev.txt
Labels: in progress

#1194 Fix click requirements.
  requirements-dev.txt
  requirements-dev.txt.in
  requirements.txt
Labels: in progress
