Repository HumanCellAtlas/data-store, pull requests merged in 2019-12, with the labels that each got.

#2649 [easy] Lowercase uuid prefixes for GET /bundles/all.
  dss-api.yml
  dss/api/bundles/__init__.py
Labels: added_to_sprint

#2657 [easy] Add GCP_PROJECT_NAME to environment.prod.
  environment.prod
Labels: added_to_sprint

#2611 DSS Operations: Bundle Reference List
  dss/operations/storage.py
  tests/test_operations.py
Labels: added_to_sprint

#2666 Eventually see dynamodb result for subscription owner.
  tests/test_subscriptions.py
Labels: added_to_sprint

#2670 Update terraform files to address deprecation warnings.
  infra/async_state_db/main.tf
  infra/buckets/gs.tf
  infra/buckets/s3.tf
  infra/collections_db/main.tf
  infra/domain/main.tf
  infra/dss-events-scribe/main.tf
  infra/elasticsearch/access_ips.tf
  infra/elasticsearch/main.tf
  infra/gcp_service_account/main.tf
  infra/subscription_v2_db/main.tf
Labels: added_to_sprint

#2685 DSS Infra: dss-lambda IAM
  iam/policy-templates/dss-lambda.json
Labels: added_to_sprint

#2683 DSS Infra: Chalice IAM Policy
  chalice/build_deploy_config.sh
Labels: DevOps, added_to_sprint

#2541 [test] Disable codecov upload on PR builds
  .codecov.yml
  .travis.yml
  README.md
Labels: DevOps

#2696 Force Codacy to use Python 3 for linting
  .codacy.yml
Labels: added_to_sprint

#2695 Use test-specific placeholder emails (closes #2665)
  tests/fixtures/datafiles/example_bundle/project_0.json
  tests/sample_doc_tombstone.json
  tests/sample_v0_index_doc_tombstone.json
  tests/sample_vx_index_doc.json
  tests/sample_vx_index_doc_tombstone.json
  tests/test_checkout.py
  tests/test_operations.py
  tests/test_server.py
  tests/test_subscriptions.py
  tests/test_utils.py
Labels: added_to_sprint
